version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  apt_packages:
    - default-jre
  jobs:
    # Install PlantUML
    pre_install:
      - curl -o ${READTHEDOCS_VIRTUALENV_PATH}/bin/plantuml.jar -L https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar
      - bash -c "echo -e '#!/bin/bash\nexec java -Djava.awt.headless=true -jar ${READTHEDOCS_VIRTUALENV_PATH}/bin/plantuml.jar \"\$@\"' > ${READTHEDOCS_VIRTUALENV_PATH}/bin/plantuml"
      - chmod +x ${READTHEDOCS_VIRTUALENV_PATH}/bin/plantuml

sphinx:
   configuration: doc/conf.py
   fail_on_warning: true

python:
  install:
    - method: pip
      path: .
      extra_requirements: [docs]