version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  apt_packages:
    - plantuml=1:1.2021.14+ds-1

sphinx:
   configuration: doc/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements: [docs]