version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-latest"
  apt_packages:
    - default-jre # for plantuml
    - graphviz # for plantuml

conda:
  environment: rtd-environment.yml

sphinx:
   configuration: doc/conf.py
   fail_on_warning: true