version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  
  # Java is required for PlantUML to generate C4 diagrams
  apt_packages:
    - plantuml
    - openjdk-17-jdk

sphinx:
   configuration: doc/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements: [docs]