version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    post_install:
      # Download the latest PlantUML jar
      - wget https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar -P /tmp/
      # Create an executable wrapper script for Sphinx
      - echo '#!/bin/sh' > /usr/local/bin/plantuml
      - echo 'java -jar /tmp/plantuml.jar "$@"' >> /usr/local/bin/plantuml
      - chmod +x /usr/local/bin/plantuml

sphinx:
   configuration: doc/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements: [docs]