# Publish a release to PyPI.

name: "Publish to PyPI"

on:
  release:
    types: [published]

jobs:
  call-ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
  publish:
    runs-on: ubuntu-latest
    needs: call-ci
    permissions:
      id-token: write
    steps:
      - name: Download standard wheels and sdist
        uses: actions/download-artifact@v8
        with:
          path: dist/
          merge-multiple: true
          pattern: cibw-*

      - name: Download WASM wheels
        uses: actions/download-artifact@v8
        with:
          name: wasm_wheel
          path: dist/

      - name: Publish distribution to PyPI
        if: github.event.release.prerelease == false
        uses: pypa/gh-action-pypi-publish@release/v1
